### ISSUE TITLE
creator 更新到2.2.0了，跑一下报错了 CCEffect似乎没有了

### ISSUE THREAD

**Issue by songxiaopeng** [ShawnZhang2015/ShaderHelper2#1]

**Comment by ShawnZhang2015** [comment]
不好意思，ShaderHelper 目前还不支持 2.2.0，我下来看看能否升级，感谢你的反馈。




------------------ 原始邮件 ------------------
发件人: "songxiaopeng"<notifications@github.com>;
发送时间: 2019年10月18日(星期五) 晚上6:39
收件人: "ShawnZhang2015/ShaderHelper2"<ShaderHelper2@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [ShawnZhang2015/ShaderHelper2] creator 更新到2.2.0了，跑一下报错了 CCEffect似乎没有了 (#1)

**Comment by MegaByte** [comment]
Any luck updating to 2.3.0?

**Comment by coder-free** [comment]
2.3.4报错
![image](https://user-images.githubusercontent.com/2630290/85385483-f1748300-b574-11ea-91ca-8ec7eb20ffe9.png)
```
TypeError: Cannot read property 'effect' of null
    at addMeshToNode (/Applications/CocosCreator/Creator/2.3.4/CocosCreator.app/Contents/Resources/app.asar/editor/page/gizmos/utils/engine/2d.js:1:1591)
    at Object.f.arrow (/Applications/CocosCreator/Creator/2.3.4/CocosCreator.app/Contents/Resources/app.asar/editor/page/gizmos/3d/elements/utils/controller-utils.js:1:573)
    at module.exports.createAxis (/Applications/CocosCreator/Creator/2.3.4/CocosCreator.app/Contents/Resources/app.asar/editor/page/gizmos/3d/elements/controller/position-controller.js:1:657)
    at module.exports.initShape (/Applications/CocosCreator/Creator/2.3.4/CocosCreator.app/Contents/Resources/app.asar/editor/page/gizmos/3d/elements/controller/position-controller.js:1:1268)
    at new module.exports (/Applications/CocosCreator/Creator/2.3.4/CocosCreator.app/Contents/Resources/app.asar/editor/page/gizmos/3d/elements/controller/position-controller.js:1:619)
    at module.exports.createController (/Applications/CocosCreator/Creator/2.3.4/CocosCreator.app/Contents/Resources/app.asar/editor/page/gizmos/3d/elements/transform/position-gizmo.js:1:552)
    at module.exports.init (/Applications/CocosCreator/Creator/2.3.4/CocosCreator.app/Contents/Resources/app.asar/editor/page/gizmos/3d/elements/transform/position-gizmo.js:1:470)
    at module.exports.init (/Applications/CocosCreator/Creator/2.3.4/CocosCreator.app/Contents/Resources/app.asar/editor/page/gizmos/2d/elements/transform/position-gizmo.js:1:372)
    at module.exports.show (/Applications/CocosCreator/Creator/2.3.4/CocosCreator.app/Contents/Resources/app.asar/editor/page/gizmos/2d/elements/gizmo.js:1:4650)
    at module.exports.update (/Applications/CocosCreator/Creator/2.3.4/CocosCreator.app/Contents/Resources/app.asar/editor/page/gizmos/2d/elements/gizmo.js:1:4263)
```
求修复！
